# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'GFinder' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GFinder

   pod 'MagicalRecord'
   pod 'SVProgressHUD'
   pod 'AFNetworking'
   pod 'SDWebImage'

  target 'GFinderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GFinderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
